### ISSUE TITLE
AttributeError: 'MLink' object has no attribute 'ai_scan_sync'

### ISSUE THREAD

**Issue by galatealab** [microdaq/PyMLink#8]
Hi. 

We encountered difficulty to connect to the microdaq. 
It is not obvious that mdaq.disconnect() must be run each time in order be able to communicate again with the mdaq.

Moreover, we noticed the following error while running the demo test. 

AttributeError                            Traceback (most recent call last)
<ipython-input-19-7a292449f9d4> in <module>
    418     mdaq.ai_scan_init([1], [-10, 10], False, 1000, -1)
    419 
--> 420     print(mdaq.ai_scan_sync.__doc__)
    421     mdaq.ai_scan_sync(8, pml.Triggers.EDGE_FALLING |  pml.Triggers.EDGE_RISING)
    422 

AttributeError: 'MLink' object has no attribute 'ai_scan_sync'

**Comment by witczenko** [comment]
Hi, 
the `ai_scan_sync` method should not be considered as part of the official API, for some reason it stayed in test section. We will clear it up with the next maintenance release. 

According to `mdaq.disconnect()` there is also possibility to use automatic connection for each function call which is enabled by default in the `MLink` construction call - `maintain_connection=False`. Please follow code snippets form `demos` directory rather than `tests`.

We will take seriously all feedback in order to improve product. We are appreciate for taking your time.
